### ISSUE TITLE
Add disable property in Z-Combobox

### ISSUE THREAD

**Issue by gsaraceno92** [ZanichelliEditore/design-system#10]
Z-Combobox is missing disable state.
The web component should receive a disabled property in order to disable the component.

**Comment by vpasquino** [comment]
Abstract: https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/master/commits/6b989de7af769f87f4598182fc07c7b79b74fc76/files/2B453759-9259-472B-8098-2846C9D506B5/layers/0EC40E0D-2CEC-4892-A064-F5EAE9E2F546?collectionId=bbdfecab-9861-4f01-8822-d3afb720770d&collectionLayerId=5dee4fe6-4645-42a8-a4f2-dcedc55c7ff1

The approved component does not have a disabled state.
