### ISSUE TITLE
z-input empty message

### ISSUE THREAD

**Issue by DarioSacco** [ZanichelliEditore/design-system#11]
When using z-input component without setting a `message`, the space needed to show the text is rendered anyways. I think that's because of the `hasmessage`'s default `true` value, also causing [this span](https://github.com/ZanichelliEditore/design-system/blob/cb8e052fa93d531af026271af29d4e8cf7e4e42a/src/components/inputs/z-input/index.tsx#L245)) to render with the class `msg_undefined`.

Perhaps the `hasmessage` property can be removed letting `message` be the source of truth.

**Comment by ufollettu** [comment]
Props `hasmessage` and `message` have different purposes. 
The input often needs to have a minimal footprint, even when the message is empty, as you can see in the examples below:

![Schermata del 2020-09-14 14-43-13](https://user-images.githubusercontent.com/67588501/93087329-af04a300-f698-11ea-8621-664324d55438.png)
![Schermata del 2020-09-14 14-43-01](https://user-images.githubusercontent.com/67588501/93087339-b0ce6680-f698-11ea-8929-1165f264a921.png)

According to [Z-input Component Sheet](https://app.abstract.com/projects/fd370780-e659-11e8-99dc-0d08537c5fde/branches/master/commits/latest/files/2B453759-9259-472B-8098-2846C9D506B5/layers/985157FA-D35E-400F-9B80-26714E9727E2?collectionId=bbdfecab-9861-4f01-8822-d3afb720770d&collectionLayerId=3c26bc40-2373-4f4d-8ae7-f1c118b59a09&mode=build&selected=610081836-B37DFF30-8739-476F-A4F3-838E0D32204A) the empty message footprint is  designed alongside the z-input component itself.

![image (8)](https://user-images.githubusercontent.com/12939926/93089329-6f8b8600-f69b-11ea-9e20-cb0a1c4c8afc.png)
