### ISSUE TITLE
Missing 'mail.png' image 

### ISSUE THREAD

**Issue by nicolocarpignoli** [ZanichelliEditore/design-system#7]
According to the [footer structure](https://github.com/ZanichelliEditore/design-system/tree/master/src/components/footer/z-footer) and [this JSON](https://staticmy.zanichelli.it/banner/2.1/banner-menu.json), there is a mail icon that is referencing a `mail.png` file. 

I found all the other referenced images [here](https://github.com/ZanichelliEditore/design-system/tree/master/src/assets/images/png) but `mail.png` is missing.

Is the JSON wrong (so the mail icon should not be added at all) or the assets folder above is actually missing the image? Thanks

**Comment by vpasquino** [comment]
The [JSON file](https://s3-eu-west-1.amazonaws.com/staticmy.zanichelli.it/banner/2.1/banner-menu.json) now uses images from S3.
